# Generated by Django 6.0.5 on 2026-06-17 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0001_initial'),
        ('creditos', '0004_alter_credito_estado_historialaprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NORMAL', 'Normal'), ('JUDICIAL', 'Judicial'), ('CASTIGO', 'Castigo / Cartera Castigada')], default='NORMAL', max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_mora', to='creditos.credito')),
                ('usuario_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GestionCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('resultado', models.CharField(choices=[('LLAMADA', 'Llamada realizada'), ('PROMESA_PAGO', 'Cliente promete pago'), ('CORREO', 'Correo enviado'), ('VISITA', 'Visita realizada'), ('SIN_CONTACTO', 'Sin contacto'), ('PAGO_PARCIAL', 'Pago parcial recibido'), ('ACUERDO_PAGO', 'Acuerdo de pago suscrito')], max_length=30)),
                ('dias_mora_snapshot', models.IntegerField(default=0)),
                ('banda_mora_snapshot', models.CharField(default='PREVENTIVA', max_length=20)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_cobranza', to='creditos.credito')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
