# Generated by Django 6.0.5 on 2026-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaahorro',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=4, default=0.035, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cuentaahorro',
            name='tipo_cuenta',
            field=models.CharField(choices=[('Tradicional', 'Ahorro Tradicional (TREA ~3.50%)'), ('Plazo Fijo', 'Depósito a Plazo Fijo (TEA 3.13% - 6.38%)'), ('CTS', 'Cuenta CTS')], default='Tradicional', max_length=50),
        ),
    ]
