# Generated by Django 6.0.6 on 2026-06-17 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_cliente_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(choices=[('VIDA', 'Seguro de Vida'), ('DESGRAVAMEN', 'Seguro de Desgravamen'), ('VEHICULAR', 'Seguro Vehicular'), ('HOGAR', 'Seguro de Hogar')], max_length=50)),
                ('prima_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='authentication.cliente')),
            ],
        ),
    ]
