# Generated by Django 6.0.5 on 2026-05-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uid_supabase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
