# Generated by Django 6.0.5 on 2026-05-13 00:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_cliente_uid_supabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='uid_supabase',
        ),
        migrations.AddField(
            model_name='cliente',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
