# Generated by Django 6.0.5 on 2026-05-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_cliente_uid_supabase_cliente_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='uid',
            field=models.UUIDField(unique=True),
        ),
    ]
