# Generated by Django 6.0.5 on 2026-06-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ASESOR', 'Asesor'), ('RIESGOS', 'Riesgos'), ('COMITE', 'Comité'), ('GERENCIA', 'Gerencia'), ('ADMIN', 'Admin')], default='CLIENTE', max_length=20),
        ),
    ]
