# Generated by Django 6.0.6 on 2026-06-09 23:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_cliente_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_credito', models.CharField(choices=[('Personal', 'Préstamo Personal'), ('Vehicular', 'Préstamo Vehicular'), ('Hipotecario', 'Crédito Hipotecario'), ('Negocio', 'Crédito para Negocio')], max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.IntegerField()),
                ('tasa_interes', models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cuotas_pagadas', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('EN_EVALUACION', 'En Evaluación'), ('APROBADO', 'Aprobado'), ('DESEMBOLSADO', 'Desembolsado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='EN_EVALUACION', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='authentication.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_tras_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.credito')),
            ],
        ),
    ]
