# Generated by Django 6.0.6 on 2026-06-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_credito_campos_financieros_pagocuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('EN_EVALUACION', 'En Evaluación'), ('EN_RIESGOS', 'En Evaluación de Riesgos'), ('EN_COMITE', 'En Comité'), ('APROBADO', 'Aprobado'), ('DESEMBOLSADO', 'Desembolsado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='EN_EVALUACION', max_length=30),
        ),
    ]
