# Generated by Django 6.0.6 on 2026-06-17 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_credito_observaciones_alter_credito_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('EN_EVALUACION', 'En Evaluación'), ('EN_RIESGOS', 'En Evaluación de Riesgos'), ('EN_COMITE', 'En Comité'), ('EN_GERENCIA', 'En Gerencia'), ('APROBADO', 'Aprobado'), ('DESEMBOLSADO', 'Desembolsado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='EN_EVALUACION', max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_aprobaciones', to='creditos.credito')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
