# Generated by Django 6.0.5 on 2026-06-28 15:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_alter_credito_estado_historialaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='tasa_moratoria',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tipo_credito',
            field=models.CharField(choices=[('Personal', 'Préstamo Personal'), ('Vehicular', 'Préstamo Vehicular'), ('Hipotecario', 'Crédito Hipotecario'), ('Negocio', 'Crédito para Negocio'), ('Microempresa', 'Crédito Microempresa')], max_length=100),
        ),
    ]
