# Generated by Django 6.0.5 on 2026-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_credito_tasa_moratoria_alter_credito_tasa_interes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='incluye_desgravamen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='incluye_multiriesgo',
            field=models.BooleanField(default=True),
        ),
    ]
